/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
.
 */
package Interfaz;

import java.io.BufferedWriter;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;

/**
 *
 * @author ncholbic
 */
public class PantallaSeleccionFicheroJson extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public PantallaSeleccionFicheroJson() throws FileNotFoundException, IOException, ParseException {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(191, 225, 248));
        
//        Calendar cal = Calendar.getInstance();
//        Date fecha = cal.getTime();
//        System.out.println(fecha);
//        SimpleDateFormat format = new SimpleDateFormat("dd-MM-yyyy HH:mm:ss");
//        String fecha2 = "Stacker_" + format.format(fecha);
//        System.out.println(fecha2);

        

//        File fichero = new File(nombre);
//        FileOutputStream fos = new FileOutputStream(fichero);
//        DataOutputStream escribir = new DataOutputStream(fos);
//        escribir.writeBytes("prueba num 2 \n");
//        escribir.writeBytes("prueba");
//        escribir.writeBytes("prueba prueba dos \n");
       
//            FileWriter fw = new FileWriter(fichero, true);
//            BufferedWriter bw = new BufferedWriter(fw);
////            FileReader fr = new FileReader(fichero);
////            BufferedReader br = new BufferedReader(fr);
//            bw.write("prueba");
//            bw.write("prueba otra");
//            bw.flush();   //no se nos puede olvidar el bw. flush()
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jCheckBoxApx = new javax.swing.JCheckBox();
        jCheckBoxAso = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setText("Indica tipo de fichero:");

        jCheckBoxApx.setBackground(new java.awt.Color(191, 225, 248));
        jCheckBoxApx.setText("APX");
        jCheckBoxApx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxApxActionPerformed(evt);
            }
        });

        jCheckBoxAso.setBackground(new java.awt.Color(191, 225, 248));
        jCheckBoxAso.setText("ASO");
        jCheckBoxAso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAsoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jCheckBoxApx)
                .addGap(28, 28, 28)
                .addComponent(jCheckBoxAso)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jCheckBoxApx)
                    .addComponent(jCheckBoxAso))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxApxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxApxActionPerformed
        PantallaApx pApx = new PantallaApx();
        pApx.setVisible(true);
        dispose();
    }//GEN-LAST:event_jCheckBoxApxActionPerformed

    private void jCheckBoxAsoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxAsoActionPerformed
        PantallaAso pAso = new PantallaAso();
        pAso.setVisible(true);
        dispose();
    }//GEN-LAST:event_jCheckBoxAsoActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(PantallaSeleccionFicheroJson.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(PantallaSeleccionFicheroJson.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(PantallaSeleccionFicheroJson.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(PantallaSeleccionFicheroJson.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new PantallaSeleccionFicheroJson().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBoxApx;
    private javax.swing.JCheckBox jCheckBoxAso;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
