/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import java.io.IOException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import Interfaz.PantallaFileChooser;
import java.io.File;
import java.io.FileReader;
import java.text.Normalizer.Form;
import javax.swing.JOptionPane;

/**
 *
 * @author ncholbic
 */
public class PantallaPreviaSeleccionFichero extends javax.swing.JFrame {
    File fichero;

    /**
     * Creates new form PantallaPreviaSeleccionFichero
     */
    public PantallaPreviaSeleccionFichero() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jButtonSeleccionFichero = new javax.swing.JButton();
        jButtonGenerarExcel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNombreFichero = new javax.swing.JTextField();
        jRadioButtonApx = new javax.swing.JRadioButton();
        jRadioButtonAso = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonSeleccionFichero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonSeleccionFichero.setText("Seleccionar fichero");
        jButtonSeleccionFichero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeleccionFicheroActionPerformed(evt);
            }
        });

        jButtonGenerarExcel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonGenerarExcel.setText("Generar excel");
        jButtonGenerarExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenerarExcelActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Indica tipo de fichero: ");

        buttonGroup.add(jRadioButtonApx);
        jRadioButtonApx.setText("APX");
        jRadioButtonApx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonApxActionPerformed(evt);
            }
        });

        buttonGroup.add(jRadioButtonAso);
        jRadioButtonAso.setText("ASO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTextFieldNombreFichero, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSeleccionFichero)
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonApx)
                        .addGap(27, 27, 27)
                        .addComponent(jRadioButtonAso)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(jButtonGenerarExcel)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSeleccionFichero)
                    .addComponent(jTextFieldNombreFichero, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jRadioButtonApx)
                    .addComponent(jRadioButtonAso))
                .addGap(32, 32, 32)
                .addComponent(jButtonGenerarExcel)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSeleccionFicheroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeleccionFicheroActionPerformed
//        PantallaFileChooser pfc = new PantallaFileChooser();
//        pfc.setVisible(true);

        //Creamos el objeto JFileChooser
        JFileChooser fc = new JFileChooser();

        //Indicamos lo que podemos seleccionar
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);

        //Creamos el filtro
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("*.XLSX", "XLSX");

        //Le indicamos el filtro
        fc.setFileFilter(filtro);

        //Abrimos la ventana, guardamos la opcion seleccionada por el usuario
        int seleccion = fc.showDialog(jLabel1, "SELECCIONAR");

        //Si el usuario, pincha en aceptar
        if (seleccion == JFileChooser.APPROVE_OPTION) {

            //Seleccionamos el fichero
            fichero = fc.getSelectedFile();

            //Ecribe la ruta del fichero seleccionado en el campo de texto
            jTextFieldNombreFichero.setText(fichero.getAbsolutePath());

            //leer y demás mierdas el fichero aquí
//    try(FileReader fr=new FileReader(fichero)){
//        String cadena="";
//        int valor=fr.read();
//        while(valor!=-1){
//            cadena=cadena+(char)valor;
//            valor=fr.read();
//        }
//        textArea.setText(cadena);
//    } catch (IOException e1) {
//        e1.printStackTrace();
//    }
        }
    }//GEN-LAST:event_jButtonSeleccionFicheroActionPerformed

    private void jButtonGenerarExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenerarExcelActionPerformed
        String tipoFichero = "";
        ProcesarExcel le = new ProcesarExcel();
        if (jRadioButtonApx.isSelected()) {
            tipoFichero = "Apx";
            le.leerExcel(fichero, tipoFichero);
            le.escribirExcelAPX();
        } else if (jRadioButtonAso.isSelected()) {
            tipoFichero = "Aso";
            le.leerExcel(fichero, tipoFichero);
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Seleccione si el fichero Excel es APX o ASO");
        }
        
    }//GEN-LAST:event_jButtonGenerarExcelActionPerformed

    private void jRadioButtonApxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonApxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonApxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPreviaSeleccionFichero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JButton jButtonGenerarExcel;
    private javax.swing.JButton jButtonSeleccionFichero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButtonApx;
    private javax.swing.JRadioButton jRadioButtonAso;
    private javax.swing.JTextField jTextFieldNombreFichero;
    // End of variables declaration//GEN-END:variables
}
