/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Modelo.Apx;
import Modelo.Aso;
import java.io.DataOutputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ncholbic
 */
public class PantallaAso extends javax.swing.JFrame {

    Aso aso;
    String isCritical;
    String responseTimeCritical;    
    String timeWindow;
    String volumen;
    String email;
    boolean aniadirLista = true;

    ArrayList<Aso> listaAso = new ArrayList();

    /**
     * Creates new form SegundaPantalla
     */
    public PantallaAso() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(191, 225, 248));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelAlarmType = new javax.swing.JLabel();
        textoAlarmType = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textoRemedyGroup = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        textoServiceOwner = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jComboBoxResponseTimeCritical = new javax.swing.JComboBox<>();
        textoSupportEmail = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        jComboBoxTimeWindow = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jComboBoxVolumen = new javax.swing.JComboBox<>();
        botonAniadir = new javax.swing.JButton();
        botonGuardar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        textoSmc = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        textoSmcName = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        textoUuaa = new javax.swing.JFormattedTextField();
        jLabel15 = new javax.swing.JLabel();
        jComboBoxCritical = new javax.swing.JComboBox<>();
        textoSupportPhone = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 255));
        setResizable(false);

        jLabelAlarmType.setText("alarmType");

        textoAlarmType.setText(" ");
        textoAlarmType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoAlarmTypeActionPerformed(evt);
            }
        });

        jLabel3.setText("remedyGroup");

        textoRemedyGroup.setText(" ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Opcional:");

        jLabel5.setText("responseTimeCritical");

        jLabel7.setText("serviceOwner");

        textoServiceOwner.setText(" ");

        jLabel8.setText("supportEmail");

        jLabel9.setText("supportPhone");

        jComboBoxResponseTimeCritical.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----", "500", "2000", "5000", "10000" }));
        jComboBoxResponseTimeCritical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxResponseTimeCriticalActionPerformed(evt);
            }
        });

        textoSupportEmail.setText(" ");

        jLabel10.setText("timeWindow");

        jComboBoxTimeWindow.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----", "24H", "WORK_HOURS", "NON_WORK_HOURS" }));
        jComboBoxTimeWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTimeWindowActionPerformed(evt);
            }
        });

        jLabel11.setText("volumen");

        jComboBoxVolumen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----", "ALTO", "MEDIO", "BAJO" }));
        jComboBoxVolumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxVolumenActionPerformed(evt);
            }
        });

        botonAniadir.setText("AÑADIR AL DOCUMENTO");
        botonAniadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAniadirActionPerformed(evt);
            }
        });

        botonGuardar.setText("GUARDAR DOCUMENTO");
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });

        jLabel12.setText("smc");

        textoSmc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoSmcActionPerformed(evt);
            }
        });

        jLabel13.setText("smcName");

        jLabel14.setText("uuaa");

        try {
            textoUuaa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("UUUU")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        textoUuaa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoUuaaActionPerformed(evt);
            }
        });

        jLabel15.setText("isCritical");

        jComboBoxCritical.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----", "CRITICO", "NOCRITICO" }));
        jComboBoxCritical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCriticalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxResponseTimeCritical, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelAlarmType)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textoAlarmType, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(109, 109, 109)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxCritical, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textoRemedyGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(textoServiceOwner, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(textoSupportEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textoSmc, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textoSmcName, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addGap(18, 18, 18)
                                        .addComponent(textoUuaa, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(13, 13, 13)
                                        .addComponent(textoSupportPhone)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBoxVolumen, 0, 133, Short.MAX_VALUE)
                                    .addComponent(jComboBoxTimeWindow, 0, 1, Short.MAX_VALUE))))))
                .addContainerGap(13, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(botonAniadir, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonGuardar)
                .addGap(54, 54, 54))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelAlarmType)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textoAlarmType, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15)
                        .addComponent(jComboBoxCritical, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textoRemedyGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jComboBoxResponseTimeCritical, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(textoServiceOwner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(textoSmc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(textoSmcName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(textoSupportEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jComboBoxTimeWindow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoSupportPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jComboBoxVolumen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(textoUuaa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAniadir, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(93, 93, 93)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(307, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textoAlarmTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoAlarmTypeActionPerformed
//        //jTextFieldAlarmType.getText();
//        System.out.println(textoAlarmType.getText());
//        aso.setAlarmType(textoAlarmType.getText());
    }//GEN-LAST:event_textoAlarmTypeActionPerformed

    private void botonAniadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAniadirActionPerformed
        
        
        aso = new Aso();
        //Validación de textoAlarmType
        if (textoAlarmType.getText().length() >= 4) {
            aso.setAlarmType(textoAlarmType.getText());           
        } else {
            if (textoAlarmType.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "El campo alarmType no puede estar vacío");
                aniadirLista = false;
            } else {
                aniadirLista = false;
                JOptionPane.showMessageDialog(rootPane, "El campo alarmType ha de contener al menos 4 caracteres");
            }
        }
       
        //Validación campo isCritical
        if (isCritical != null) {
            if (isCritical.equals("----")) {
                JOptionPane.showMessageDialog(rootPane, "Selección del campo isCritical no válida");
                aniadirLista = false;
            } else {
                aso.setIsCritical(isCritical);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Seleccione una opción de isCritical");
            aniadirLista = false;
        }

        //Validación de textoRemedyGroup
        if (textoRemedyGroup.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "El campo remedyGroup no puede estar vacío");
            aniadirLista = false;
        } else {
            aso.setRemedyGroup(textoRemedyGroup.getText());
            //aniadirLista = true;
        }

        aso.setResponseTimeCritical(responseTimeCritical);

        //Validación de textoServiceOwner
        if (textoServiceOwner.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "El campo serviceOwner no puede estar vacío");
            aniadirLista = false;
        } else {
            aso.setServiceOwner(textoServiceOwner.getText());
        }
        
        //Validación campo smc
        if (textoSmc.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "El campo smc no puede estar vacío");
            aniadirLista = false;
        } else {
            aso.setSmc(textoSmc.getText());
        }
        
        //Validación campo smcName
        if (textoSmcName.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "El campo smcName no puede estar vacío");
            aniadirLista = false;
        } else {
            aso.setSmcName(textoSmcName.getText());
        }
        
        //Validación de textoSupportEmail
        email = textoSupportEmail.getText();
        //System.out.println(email);
        String EMAIL_PATTERN = "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";
        boolean resultado = email.trim().matches(EMAIL_PATTERN);
        //System.out.println(resultado);
        if (resultado == true) {
            aso.setSupportEmail(email);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Introduzca un formato de email válido");
            aniadirLista = false;
        }

        //Validación de móvil
        //Primero validamos la longitud del num telefono
        if (textoSupportPhone.getText().trim().length() != 9) { //pongo que sea 11 el length porque con el formato que he introducido, pone que son 11 dígitos 
            //el teléfono y no 9 (por dos espacios, que no me quita aunque use el método trim()          
            JOptionPane.showMessageDialog(rootPane, "Introduzca nueve dígitos, por favor");
            aniadirLista = false;
        }

        //Ahora validamos que empiece por 6 o 7
        boolean empiezaSeis = textoSupportPhone.getText().startsWith("6");
        boolean empiezaSiete = textoSupportPhone.getText().startsWith("7");
        if (empiezaSeis == false && empiezaSiete == false) {
            JOptionPane.showMessageDialog(rootPane, "Introduzca un formato de teléfono válido");
            aniadirLista = false;
        } else {
            aso.setSupportPhone(textoSupportPhone.getText());
        }

        //Validación de timeWindow
        if (timeWindow != null) {
            if (timeWindow.equals("----")) {
                JOptionPane.showMessageDialog(rootPane, "Selección del campo timeWindow no válida");
                aniadirLista = false;
            } else {
                aso.setTimeWindow(timeWindow);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Seleccione una opción de timeWindow");
            aniadirLista = false;
        }

        if (textoUuaa.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "El campo uuaa ha de contener 4 caracteres");
            aniadirLista = false;
        } else {                       
            aso.setUuaa(textoSmcName.getText());
        }
        
        //Validación de volumen
        if (volumen != null) {
            if (volumen.equals("----")) {
                JOptionPane.showMessageDialog(rootPane, "Selección del campo volumen no válida");
                aniadirLista = false;
            } else {
                aso.setVolumen(volumen);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Seleccione una opción de volumen");
            aniadirLista = false;
        }

        if (aniadirLista == true){
        listaAso.add(aso);

        //Ahora hacemos un reset de todos los valores para poder añadir más
        textoAlarmType.setText("");
        jComboBoxCritical.setSelectedItem("----");
        textoRemedyGroup.setText("");
        textoSmc.setText("");
        textoSmcName.setText("");
        jComboBoxResponseTimeCritical.setSelectedItem("----");
        textoServiceOwner.setText("");
        textoSupportEmail.setText("");
        textoSupportPhone.setText("");
        jComboBoxTimeWindow.setSelectedItem("----");
        textoUuaa.setText("");
        jComboBoxVolumen.setSelectedItem("----");
        }
        
        aniadirLista = true;
//        jComboBoxResponseTimeCritical.setSelectedItem("----");
//        jComboBoxCritical.setSelectedItem("----");


    }//GEN-LAST:event_botonAniadirActionPerformed

    private void jComboBoxResponseTimeCriticalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxResponseTimeCriticalActionPerformed
        responseTimeCritical = jComboBoxResponseTimeCritical.getSelectedItem().toString();
    }//GEN-LAST:event_jComboBoxResponseTimeCriticalActionPerformed

    private void jComboBoxTimeWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTimeWindowActionPerformed
        timeWindow = jComboBoxTimeWindow.getSelectedItem().toString();

    }//GEN-LAST:event_jComboBoxTimeWindowActionPerformed

    private void jComboBoxVolumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxVolumenActionPerformed
        volumen = jComboBoxVolumen.getSelectedItem().toString();
    }//GEN-LAST:event_jComboBoxVolumenActionPerformed

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        FileOutputStream fichero = null;
        try {
            //JsonMapper jsonMapper = new JsonMapper();
            Calendar cal = Calendar.getInstance();
            Date fecha = cal.getTime();
            //System.out.println(fecha);
            SimpleDateFormat format = new SimpleDateFormat("dd-MM-yyyy HH_mm_ss");
            String nombre = "Stacker " + format.format(fecha) + ".json";
            System.out.println(nombre);
            fichero = new FileOutputStream(nombre);
            DataOutputStream escribir = new DataOutputStream(fichero);

            for (int i = 0; i < listaAso.size(); i++) {
                //System.out.println(listaAso.get(i).toString());
                if (i == 0) {
                    escribir.writeBytes("[");
                }
                escribir.writeBytes(listaAso.get(i).toString());
                //jsonMapper.writeValue(fichero, listaAso.get(i).toString());
                if (i == listaAso.size() - 1) {
                    escribir.writeBytes("]");
                } else {
                    escribir.writeBytes(", \n");
                }
                    
//RECORRER TODOS LOS ITEMS DEL ARRAY Y ESCRIBIR EL FICHERO DE UNA
            }JOptionPane.showMessageDialog(rootPane, "Archivo guardado correctamente. Puede añadir más líneas al documento o cerrar el programa.");
        }catch (FileNotFoundException ex) {
            Logger.getLogger(PantallaAso.class.getName()).log(Level.SEVERE, null, ex);
        }catch (IOException ex) {
            Logger.getLogger(PantallaAso.class.getName()).log(Level.SEVERE, null, ex);
          }
        
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void textoSmcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoSmcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoSmcActionPerformed

    private void jComboBoxCriticalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCriticalActionPerformed
        isCritical = jComboBoxCritical.getSelectedItem().toString();
    }//GEN-LAST:event_jComboBoxCriticalActionPerformed

    private void textoUuaaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoUuaaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoUuaaActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
  
        //</editor-fold>
   

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaAso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAniadir;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JComboBox<String> jComboBoxCritical;
    private javax.swing.JComboBox<String> jComboBoxResponseTimeCritical;
    private javax.swing.JComboBox<String> jComboBoxTimeWindow;
    private javax.swing.JComboBox<String> jComboBoxVolumen;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelAlarmType;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField textoAlarmType;
    private javax.swing.JTextField textoRemedyGroup;
    private javax.swing.JTextField textoServiceOwner;
    private javax.swing.JTextField textoSmc;
    private javax.swing.JTextField textoSmcName;
    private javax.swing.JFormattedTextField textoSupportEmail;
    private javax.swing.JTextField textoSupportPhone;
    private javax.swing.JFormattedTextField textoUuaa;
    // End of variables declaration//GEN-END:variables
}
